version: '3.8'

services:
  tgvmax-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./server/data:/app/server/data
    restart: unless-stopped 